apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /html
    command: ["sh", "-c", "while true; do date >> /html/index.html; sleep 1; done"]
  volumes:
  - name: shared-data
    emptyDir: {}
