apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
      name: http
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    livenessProbe:
      httpGet:
        path: /healthy
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 0
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 3
