apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: demo-container
    image: europe-central2-docker.pkg.dev/wise-coyote-417310/test/burylo_demo:v2.0.0
    ports:
    - containerPort: 8000
      name: http
